name: youtube_to_blog
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  google_generative_ai: ^0.4.7
  http: ^1.5.0
  io: ^1.0.5
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
